apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-master
  labels:
    app: perf-loadgen
    component: master
spec:
  type: {{ .Values.service.type }}
  selector:
    app: perf-loadgen
    component: master
  ports:
  - port: {{ .Values.service.dashboardPort }}
    targetPort: dashboard
    name: dashboard
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-worker
  labels:
    app: perf-loadgen
    component: worker
spec:
  clusterIP: None
  selector:
    app: perf-loadgen
    component: worker
  ports:
  - port: {{ .Values.service.workerPort }}
    targetPort: worker
    name: worker
